let codemode = "html";

let codeout_interpreta = function (modo) {
  codemode = modo;
};

let codeout = function (p) {
  let id = windowmanager.createframe("", {
    HTML: "HTML",
    Javascript: "Javascript",
    Typescript: "Typescript",
  });

  let code = `
    
        <style>

        #codeoutput_${id} {
                         width: calc(100% - 0px);
                         height: calc(100% - 14px);
                         border: 0;
                         outline: 0 !important;
                         background-color: #fffef5;
                         font-size: 14px;
                         line-height: 20px;
                         margin-top: 0 !important;
                         overflow-x: hidden;"
        }

        </style>

        <iframe id='codeoutput_${id}' frameborder='0'></iframe>

    `;

  document.getElementById("res" + id).innerHTML = code;
  document.getElementById("res" + id).style.height = "calc(100% - 5rem + 13px)";
  document.getElementById("res" + id).style.maxHeight =
    "calc(100% - 5rem + 13px)";
  document.getElementById("res" + id).style.width = "calc(100% - 1rem + 0px)";

  document.getElementById("res" + id).style.paddingRight = 0;
  document.getElementById("res" + id).style.paddingTop = 0;

  let nditor = id.match(/(t_)(\d{1,3})/)[2];

  document
    .getElementById("t_f" + nditor)
    .addEventListener("input", function (e) {
      /*

        namecodex["t_" + nditor] = document.getElementById(
          "t_f" + nditor,
            ).value;

        */

      let iframe = document.getElementById("codeoutput_" + id);

      let iframeDoc = iframe.contentDocument || iframe.contentWindow.document;

      let htmlContent = `
  <!DOCTYPE html>
  <html>
  <head>
    <title>Dynamic Iframe Content</title>
    <style>
      body {
        background-color: lightblue;
        font-family: sans-serif;
        padding: 20px;
      }
    </style>
  </head>
  <body>
    <h1>Hello from the iframe!</h1>
    <p>This content was generated by JavaScript.</p>
  </body>
  </html>
`;
      iframeDoc.open();
      iframeDoc.write(htmlContent);
      iframeDoc.close();
    });

  document.getElementById("m_f" + nditor).innerHTML = `
  
    <a onclick="codeout_interpreta('html');">HTML</a><a onclick="codeout_interpreta('javascript'););">Javascript</a><a onclick="codeout_interpreta('P5');">P5</a>
  `;
};
